"""SQLite persistence layer for employees and support tickets.

The database is created and seeded automatically on first use so the
evaluator can run the application immediately without any manual setup.
"""

from __future__ import annotations

import json
import random
import re
import sqlite3
import string
from contextlib import contextmanager
from datetime import datetime
from pathlib import Path
from typing import Any

from src.config import DB_PATH, EMAIL_DOMAIN, EMPLOYEES_JSON, SEED_TICKETS_JSON
from src.logging_config import logger

SCHEMA = """
CREATE TABLE IF NOT EXISTS employees (
    employee_id TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    email       TEXT NOT NULL,
    department  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tickets (
    ticket_id    TEXT PRIMARY KEY,
    employee_id  TEXT NOT NULL,
    category     TEXT NOT NULL,
    description  TEXT NOT NULL,
    status       TEXT NOT NULL DEFAULT 'Open',
    created_at   TEXT NOT NULL,
    FOREIGN KEY (employee_id) REFERENCES employees (employee_id)
);

CREATE TABLE IF NOT EXISTS chats (
    chat_id      TEXT PRIMARY KEY,
    thread_id    TEXT NOT NULL,
    title        TEXT NOT NULL DEFAULT 'New Chat',
    history_json TEXT NOT NULL DEFAULT '[]',
    created_at   TEXT NOT NULL,
    updated_at   TEXT NOT NULL
);
"""


@contextmanager
def get_connection():
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def init_db(force_reseed: bool = False) -> None:
    """Create tables if needed and seed them from the local JSON files.

    Idempotent: seeding only happens when the relevant table is empty,
    unless ``force_reseed`` is True (used by tests to reset state).
    """
    with get_connection() as conn:
        conn.executescript(SCHEMA)

        employee_count = conn.execute("SELECT COUNT(*) FROM employees").fetchone()[0]
        if force_reseed or employee_count == 0:
            _seed_employees(conn)

        ticket_count = conn.execute("SELECT COUNT(*) FROM tickets").fetchone()[0]
        if force_reseed or ticket_count == 0:
            _seed_tickets(conn)

    logger.info("Database ready at %s", DB_PATH)


def _seed_employees(conn: sqlite3.Connection) -> None:
    employees = _load_json(EMPLOYEES_JSON)
    conn.execute("DELETE FROM employees")
    conn.executemany(
        "INSERT INTO employees (employee_id, name, email, department) VALUES (?, ?, ?, ?)",
        [(e["employee_id"], e["name"], e["email"], e["department"]) for e in employees],
    )
    logger.info("Seeded %d employees", len(employees))


def _seed_tickets(conn: sqlite3.Connection) -> None:
    tickets = _load_json(SEED_TICKETS_JSON)
    conn.execute("DELETE FROM tickets")
    conn.executemany(
        """INSERT INTO tickets (ticket_id, employee_id, category, description, status, created_at)
           VALUES (?, ?, ?, ?, ?, ?)""",
        [
            (
                t["ticket_id"],
                t["employee_id"],
                t["category"],
                t["description"],
                t["status"],
                t["created_at"],
            )
            for t in tickets
        ],
    )
    logger.info("Seeded %d tickets", len(tickets))


def _load_json(path: Path) -> list[dict[str, Any]]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


# --- Employee helpers --------------------------------------------------------

def get_employee(employee_id: str) -> dict[str, Any] | None:
    with get_connection() as conn:
        row = conn.execute(
            "SELECT * FROM employees WHERE employee_id = ?", (employee_id.strip().upper(),)
        ).fetchone()
        return dict(row) if row else None


def generate_unique_employee_email(local_prefix: str) -> str:
    """Build a unique company email for a new employee from a name-based prefix.

    Multiple employees can share the same first + last name, so emails are
    disambiguated with an incrementing numeric suffix rather than being
    rejected as duplicates:

        1st person named "Jane Doe"  -> jane_doe@<domain>
        2nd person named "Jane Doe"  -> jane_doe1@<domain>
        3rd person named "Jane Doe"  -> jane_doe2@<domain>

    ``local_prefix`` should already be the slugified "firstname_lastname"
    portion (lowercase, no domain). The suffix count is derived from how
    many existing employees already have an email matching this exact
    pattern, so it stays correct even if the earlier numbers were seeded
    rather than generated by this function.
    """
    pattern = re.compile(rf"^{re.escape(local_prefix)}(\d*)@{re.escape(EMAIL_DOMAIN)}$")

    with get_connection() as conn:
        rows = conn.execute("SELECT email FROM employees").fetchall()

    existing_count = sum(1 for row in rows if pattern.match(row["email"]))

    if existing_count == 0:
        return f"{local_prefix}@{EMAIL_DOMAIN}"
    return f"{local_prefix}{existing_count}@{EMAIL_DOMAIN}"


def create_employee(name: str, email: str, department: str) -> dict[str, Any]:
    """Register a brand-new employee and return their generated employee record.

    The employee_id is generated server-side (never supplied/invented by the
    LLM) so IDs stay consistent with the existing EMP#### format and cannot
    collide with a seeded or previously created employee.
    """
    employee_id = _generate_employee_id()

    with get_connection() as conn:
        conn.execute(
            "INSERT INTO employees (employee_id, name, email, department) VALUES (?, ?, ?, ?)",
            (employee_id, name.strip(), email.strip(), department.strip()),
        )

    logger.info("Registered new employee %s (%s)", employee_id, name)
    return {
        "employee_id": employee_id,
        "name": name.strip(),
        "email": email.strip(),
        "department": department.strip(),
    }


def _generate_employee_id() -> str:
    suffix = "".join(random.choices(string.digits, k=4))
    candidate = f"EMP{suffix}"
    with get_connection() as conn:
        exists = conn.execute(
            "SELECT 1 FROM employees WHERE employee_id = ?", (candidate,)
        ).fetchone()
    if exists:
        return _generate_employee_id()
    return candidate


# --- Ticket helpers -----------------------------------------------------------

def find_tickets(
    employee_id: str | None = None,
    ticket_id: str | None = None,
    keyword: str | None = None,
) -> list[dict[str, Any]]:
    query = "SELECT * FROM tickets WHERE 1=1"
    params: list[Any] = []

    if ticket_id:
        query += " AND ticket_id = ?"
        params.append(ticket_id.strip().upper())
    if employee_id:
        query += " AND employee_id = ?"
        params.append(employee_id.strip().upper())
    if keyword:
        query += " AND (LOWER(description) LIKE ? OR LOWER(category) LIKE ?)"
        like = f"%{keyword.strip().lower()}%"
        params.extend([like, like])

    query += " ORDER BY created_at DESC"

    with get_connection() as conn:
        rows = conn.execute(query, params).fetchall()
        return [dict(r) for r in rows]


def find_open_ticket_for_duplicate_check(employee_id: str, category: str) -> dict[str, Any] | None:
    """Look for an existing non-resolved ticket of the same category for this employee."""
    with get_connection() as conn:
        row = conn.execute(
            """SELECT * FROM tickets
               WHERE employee_id = ? AND category = ? AND status != 'Resolved'
               ORDER BY created_at DESC LIMIT 1""",
            (employee_id.strip().upper(), category),
        ).fetchone()
        return dict(row) if row else None


def create_ticket(employee_id: str, category: str, description: str) -> dict[str, Any]:
    ticket_id = _generate_ticket_id()
    created_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    with get_connection() as conn:
        conn.execute(
            """INSERT INTO tickets (ticket_id, employee_id, category, description, status, created_at)
               VALUES (?, ?, ?, ?, 'Open', ?)""",
            (ticket_id, employee_id.strip().upper(), category, description, created_at),
        )

    logger.info("Created ticket %s for %s", ticket_id, employee_id)
    return {
        "ticket_id": ticket_id,
        "employee_id": employee_id.strip().upper(),
        "category": category,
        "description": description,
        "status": "Open",
        "created_at": created_at,
    }


def _generate_ticket_id() -> str:
    suffix = "".join(random.choices(string.digits, k=4))
    candidate = f"TCK-{suffix}"
    # Extremely unlikely to collide given the seed data, but check anyway.
    with get_connection() as conn:
        exists = conn.execute(
            "SELECT 1 FROM tickets WHERE ticket_id = ?", (candidate,)
        ).fetchone()
    if exists:
        return _generate_ticket_id()
    return candidate


# --- Chat history persistence -------------------------------------------------
# Chat metadata + the rendered message history (for the Streamlit sidebar) are
# stored here so chats survive an app restart. The LangGraph conversation
# state itself (used to actually run the agent) is stored separately in
# CHECKPOINT_DB_PATH via LangGraph's own SqliteSaver -- see src/graph.py.

def create_chat(chat_id: str, thread_id: str, title: str = "New Chat") -> None:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with get_connection() as conn:
        conn.execute(
            """INSERT INTO chats (chat_id, thread_id, title, history_json, created_at, updated_at)
               VALUES (?, ?, ?, '[]', ?, ?)""",
            (chat_id, thread_id, title, now, now),
        )
    logger.info("Created chat %s (thread_id=%s)", chat_id, thread_id)


def list_chats() -> list[dict[str, Any]]:
    """Return all chats, most recently updated first (without the full history payload)."""
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT chat_id, thread_id, title, created_at, updated_at FROM chats "
            "ORDER BY updated_at DESC"
        ).fetchall()
        return [dict(r) for r in rows]


def get_chat(chat_id: str) -> dict[str, Any] | None:
    with get_connection() as conn:
        row = conn.execute("SELECT * FROM chats WHERE chat_id = ?", (chat_id,)).fetchone()
    if not row:
        return None
    chat = dict(row)
    chat["history"] = json.loads(chat.pop("history_json"))
    return chat


def update_chat(chat_id: str, *, title: str | None = None, history: list | None = None) -> None:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    fields = ["updated_at = ?"]
    params: list[Any] = [now]

    if title is not None:
        fields.append("title = ?")
        params.append(title)
    if history is not None:
        fields.append("history_json = ?")
        params.append(json.dumps(history))

    params.append(chat_id)
    with get_connection() as conn:
        conn.execute(f"UPDATE chats SET {', '.join(fields)} WHERE chat_id = ?", params)


def delete_chat(chat_id: str) -> None:
    with get_connection() as conn:
        conn.execute("DELETE FROM chats WHERE chat_id = ?", (chat_id,))
    logger.info("Deleted chat %s", chat_id)
